<?php

$labels = array();
$labels['keyboard_shortcuts'] = 'Keyboard shortcuts';
$labels['show'] = 'Show';
$labels['help'] = 'Help';
$labels['selectallvisiblemessages'] = 'Select all visible messages';
$labels['markallvisiblemessagesasread'] = 'Mark all visible messages as read';
$labels['markselected'] = 'Mark selected message(s) as read or unread';
$labels['title'] = 'Shortcuts';
$labels['createfrommail'] = 'Save as event';
$labels['arialabelcalendarview'] = 'Calendar view';
$labels['locate_folder_with_dialog'] = 'Locate folder (with dialog)';
$labels['create_folder_contextual'] = 'Create folder (with dialog)';
$labels['message_copy_contextual'] = 'Copy message(s) to folder (with dialog)';
$labels['message_move_contextual'] = 'Move message(s) to folder (with dialog)';

?>
