<?php

$labels = array();
$labels['keyboard_shortcuts'] = 'Raccourcis clavier';
$labels['show'] = 'Voir';
$labels['help'] = 'Aide';
$labels['selectallvisiblemessages'] = 'Sélectionner tous les messages visibles';
$labels['markallvisiblemessagesasread'] = 'Marquer tous les messages visibles comme lus';
$labels['markselected'] = 'Marquer les messages sélectionnés comme lus ou non-lus';
$labels['title'] = 'Raccourcis';

$labels['locate_folder_with_dialog'] = 'Localiser un dossier (boîte de dialogue)';
$labels['create_folder_contextual'] = 'Créer un dossier (boîte de dialogue contextuelle)';
$labels['message_copy_contextual'] = 'Copier le ou les messages vers un dossier (boîte de dialogue)';
$labels['message_move_contextual'] = 'Déplacer le ou les messages vers un dossier (boîte de dialogue)';
?>
