<?php

$labels = array();
$labels['keyboard_shortcuts'] = 'Raccourcis clavier';
$labels['show'] = 'Voir';
$labels['help'] = 'Aide';
$labels['selectallvisiblemessages'] = 'Sélectionner tous les messages visibles';
$labels['markallvisiblemessagesasread'] = 'Marquer tous les messages visibles comme lus';
$labels['markselected'] = 'Marquer les messages sélectionnés comme lus ou non-lus';
$labels['title'] = 'Raccourcis';

?>
